name: gitHubActionsTest

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches: [ master ]

#workflow start ,it can contain 1 or more jobs
jobs:
  # Set the job key. The key is displayed as the job name when a job name is not provided
  gitHubActionsTest:
    # Name the Job
    name: Job name test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    #https://github.com/marketplace?type=actions&query=java 
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: gitHubActionsTest Checkout code
        uses: actions/checkout@v2

      #
      - name: Run Java Program
       steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
            with:
                java-version: '9.0.4' # The JDK version to make available on the path.
                java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
                architecture: x64 # (x64 or x86) - defaults to x64
        - run: java -cp java printHello.java
